### ISSUE TITLE
Add support for rule-based reasoners

### ISSUE THREAD

**Issue by gaurav** [phyloref/jphyloref#21]
We've previously discussed using rule-based reasoners to speed up reasoning on large phylogenies (see the section *A review of our software development plan* from our blog post [on our first Duke University meeting](https://www.phyloref.org/blog/2018/01/first-duke-university-meeting/)). This isn't urgent right now, since FaCT++ is fast enough for our immediate needs, but it might be worth thinking about this while planning the integration of new reasoners.

A rule-based reasoner would require rules to be developed for generating the inferences we need in [SPARQL](https://en.wikipedia.org/wiki/SPARQL)/[Cypher](https://neo4j.com/developer/cypher-query-language/)/[SWRL](https://en.wikipedia.org/wiki/Semantic_Web_Rule_Language) or a custom language. This would then be executed by a rule-based reasoner such as [Arachne](https://github.com/balhoff/arachne) or [HyLAR](https://github.com/ucbl/HyLAR-Reasoner).

Developing it in within JPhyloRef would allow us to re-use the existing code to identify which queries we need and to test them using the `test` and `webserver` commands. Once it is has been successfully integrated here, we could try to integrate them directly into the Curation Tool, thus removing the dependency on JPhyloRef entirely.

**Comment by gaurav** [comment]
If I understand [OWL RL](https://www.w3.org/TR/owl2-profiles/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules) correctly, we'll need to implement our own rules to support terms like `propertyChainAxiom` (which we need to implement `has_Sibling`). I think that means we'll need to write our own rules, in which case this would be best implemented in JPhyloRef with the following steps (which I think belongs in this repository):
- 1. Add a rule-based OWLAPI-supporting reasoner as an optional OWL reasoner into JPhyloRef.
- 2. Develop the necessary rules needed to implement phyloreferencing.
- 3. Keep testing with OWL and JSON files we know work elsewhere until we have all functionality working with our set of rules.

We could also think about simplifying our ontology so that it is in the OWL RL profile, such as by replacing `propertyChainAxiom` with some other terms, which would be an issue for the Phyloref Ontology.

Am I right in thinking that these are our two options, or am I missing something?

**Comment by hlapp** [comment]
No, a standard RL reasoner should read the axioms, not separately stated rules. OWL RL is an OWL expressivity profile, not a separate language or something.

**Comment by gaurav** [comment]
Sounds good! I've filed an issue to support OWL RL in the Phyloref ontology at phyloref/phyloref-ontology#25. I'll close this issue for now as we don't need any additional support for rule-based reasoners in JPhyloRef, but we can open a new one if we run into any issues while setting up an OWL RL profile.
