### ISSUE TITLE
Set up hosting JPhyloRef on a server

### ISSUE THREAD

**Issue by gaurav** [phyloref/jphyloref#37]
I currently run JPhyloRef locally when demonstrating the Curation Tool. If we'd like other curators to be able to reason with it, we will need to run JPhyloRef on a server somewhere. This issue will track trying out trying out different options to achieve this.

Heroku might be an option: it's free for limited use and has [support for Java](https://devcenter.heroku.com/categories/java-support). If [increased computing resources](https://www.heroku.com/pricing) are needed, they are charged by the second, which would work well here, as reasoning will likely only be used for a few minutes a day.

**Comment by ncellinese** [comment]
I have plenty of allocation with hiperGator here and you have an account too.

**Comment by gaurav** [comment]
Yup, I know! But UF Research Computing has indicated to me that "HiPerGator allocation is used for running analyses on HiPerGator. If you want to have web applications with public access it's a separate service with the capabilities and parameters I already described in detail", so I don't think we can use that allocation for hosting a web service anyway. I'll go meet with him once I'm back in Gainesville and figure out exactly what our possibilities are here.

We will eventually use HiPerGator to resolve all our phyloreferences against the Open Tree of Life, but I think we'll try that out once we've created the Clade Ontology in the next couple of months.

**Comment by ncellinese** [comment]
Not true and Yes, we can. Just come and talk to me. I am moving RegNum in there as we speak.

Nico

**Comment by gaurav** [comment]
I tried running JPhyloRef on Heroku last week: it looks like it won't work for us after all since [their dynos are limited to 512MB of memory](https://devcenter.heroku.com/articles/limits#dyno-memory); running JPhyloRef on a relatively small ontology results in an out-of-memory error.

I met with UF's Research Computing (UFRC) last week, and it looks like the best way to get JPhyloRef hosted with them would be to write a small Node.js HTTP server application hosted on UFRC's web hosting infrastructure (PubApps) that would accept input jobs as JSON files, start JPhyloRef on a compute node on the UFRC system, and return a token to the Authoring Tool. The Authoring Tool would then have to poll the server app for the reasoning results. This approach would require finding or writing the job manager HTTP server application and modifying JPhyloRef so that it can report on phyloreference resolution on the command line. We would have to think about setting up API keys or other systems for preventing overloading of this system.

I've confirmed that JPhyloRef runs fine on the UFRC's high-performance computing system. Unfortunately, PubApps uses an older version of Java that the OWLAPI library we use doesn't support, so I've put in a request for them to upgrade it. Once that happens, I should be able to test the feasibility of this approach pretty quickly.

**Comment by gaurav** [comment]
We have now set up JPhyloRef on a server (and documented the process in PR #59), and have published a website on Github Pages that can reason over ontologies (phyloref/open-tree-resolver#12) at https://www.phyloref.org/open-tree-resolver/. Closing.
