### ISSUE TITLE
Write up manuscript to submit to JOSS

### ISSUE THREAD

**Issue by gaurav** [phyloref/jphyloref#69]
The [Journal of Open Source Software](https://joss.theoj.org/) might be a good venue for a short paper that describes JPhyloRef, explains why it exists and how it works. The [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) are short and straightforward.

**Comment by ncellinese** [comment]
Perfect!

**Comment by gaurav** [comment]
Done in PR #79, closing.
